### ISSUE TITLE
大大求救啊！！！docker使用时出现了无法连接redis的问题

### ISSUE THREAD

**Issue by TaoRone** [CareyWang/MyUrls#33]
两天了一直没解决这个问题……快崩溃了

问题描述：
后台curl -i http://s2-hk5.sky.ceo/short和curl -i http://127.0.0.1/short
均会在等待十几秒后返回  短链接不存在或已过期
redis中无新的key增加
docker logs myurls会提示
```
[GIN] 2023/07/23 - 03:57:52 | 200 |    1.277873ms |   194.29.187.* | GET      "/"
[GIN] 2023/07/23 - 03:58:14 | 200 | 30.015488771s |   194.29.187.* | POST     "/short"
[GIN] 2023/07/23 - 03:58:18 | 200 |     161.564µs |   194.29.187.* | GET      "/"
[GIN] 2023/07/23 - 03:58:26 | 200 | 30.003869954s |   194.29.187.* | POST     "/short"
[GIN] 2023/07/23 - 03:58:51 | 200 | 30.022925521s |   194.29.187.* | POST     "/short"
[GIN] 2023/07/23 - 04:05:18 | 404 | 30.029518236s |  95.214.1**.* | GET      "/short"
[GIN] 2023/07/23 - 04:06:00 | 404 | 30.029486231s |      172.22.0.1 | GET      "/short"
```

感觉哪里出了问题，myurls没能成功访问redis

补充一点，直接使用默认的docker compose也会有类似的问题……

# 配置如下：
env文件
```
MYURLS_PORT=9002
MYURLS_DOMAIN=s2-hk5.sky.ceo
MYURLS_TTL=180
```

index.html
```
const backend = 'https://s2-hk5.sky.ceo' 这里无论http还是https都会出现问题
```

docker compose
对这个配置稍微进行了修改
手动redis-cli -h 127.0.0.1 -p 9003访问redis正常
```
version: "3"
services:
  myurls:
    build: .
    container_name: myurls
    restart: always
    env_file: .env
    ports:
      - "${MYURLS_PORT}:8002"
    volumes:
      - ./data/myurls/logs:/app/logs
    depends_on:
      - myurls-redis
    entrypoint: ["/app/myurls", "-domain", "${MYURLS_DOMAIN}", "-conn", "myurls-redis:6379", "-passwd", "123123", "-ttl", "${MYURLS_TTL}"]
    command: redis-server --requirepass fdsaf342

  myurls-redis:
    image: "redis:6"
    container_name: myurls-redis
    restart: always
    volumes:
      - ./data/redis:/data
    expose:
      - "6379"
    ports:
      - 9003:6379
    command: redis-server --requirepass 123123
```

nginx配置（实际上是amh的配置）
```
server {
	listen 80; listen [::]:80; #listen end
	server_name s2-hk5.sky.ceo; #server_name end
	index index.html index.htm index.php; #index end

	root  /home/wwwroot/Lngx_hk5_vps/domain/s2-hk5.sky.ceo/web; #root end
	include /home/wwwroot/Lngx_hk5_vps/rewrite/amh.conf; #rewrite end

	proxy_cache off; #proxy_cache end
	proxy_temp_path /home/wwwroot/Lngx_hk5_vps/cache_temp;
	proxy_cache_key $scheme://$host$request_uri;
	proxy_cache_valid 200 304 12h; #cache_valid end
	proxy_connect_timeout 60s; #connect_timeout end


	location / {
		default_type text/html;
		subs_filter_types text/css text/xml; #subs_filtert end
 		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
 		proxy_set_header X-Forwarded-Proto $scheme; #X-Forwarded-Proto end
		proxy_set_header X-Real-IP  $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Referer $http_referer; #header_referer end
		proxy_set_header Host $host; #header_host end
		proxy_pass http://127.0.0.1:8002; #proxy_pass end
		proxy_set_header Accept-Encoding "";
		add_header 'Access-Control-Allow-Origin' '*';
	}

	access_log /home/wwwroot/Lngx_hk5_vps/logs/s2-hk5.sky.ceo-access.log combined; #access_log end
	error_log /home/wwwroot/Lngx_hk5_vps/logs/s2-hk5.sky.ceo-error.log crit; #error_log end
}
```
